import '../ArvenScans_e2e';
import '../AsmodeusScans_e2e';
import '../CasaComic_e2e';
import '../GenzToon_e2e';
import '../GrimScans_e2e';
import '../NecroScans_e2e';
import '../ReaperScansFR_e2e';
import '../RezoScans_e2e';
import '../SerenityScans_e2e';