import '../MangaBTT_e2e';
import '../MangaRaw1001_e2e';
import '../MangaRaw18_e2e';
import '../NetTruyenOK_e2e';
import '../NetTruyenPlus_e2e';
import '../NetTruyenViet_e2e';
import '../NetTruyenZZZ_e2e';
import '../NhatTruyen_e2e';
import '../TruyenTranhOnline_e2e';