name: Continuous Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Publish Web-Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install NPM Packages
        run: npm install
      - name: Code Inspection
        run: npm run check
      - name: Unit & Component Tests
        run: npm run test
      - name: Build Web-Application
        run: npm run build --workspace=web
      - name: Deploy App to CloudFlare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./web/build --project-name=haruneko --commit-dirty=true
      - name: Build Documentation
        run: npm run build --workspace=docs
      - name: Deploy Docs to CloudFlare
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./docs/.vitepress/dist --project-name=haruneko-docs --commit-dirty=true