name: Pull Request

on: pull_request

jobs:
  pr-integration:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Starting X Virtual Frame Buffer (Port 99)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          #sudo apt-get update
          #sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgconf-2-4
          sudo /usr/bin/Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          disown -ar # remove all running jobs (e.g. xvfb) from the job table of this bash process
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Update NPM
        run: npm install -g npm@8 --registry=https://registry.npmjs.org
      - name: Install NPM Packages
        run: npm install
      - name: Code Inspection
        run: npm run check
      - name: Unit & Component Tests
        run: npm run test
      - name: Test
        env:
          DISPLAY: ':99'
        run: npm run test:e2e